### ISSUE TITLE
Publish 1.0.1 artifacts for 2.10

### ISSUE THREAD

**Issue by nrinaudo** [propensive/contextual#11]
Happy to help with this, but it needs to happen, 1.0.1 was published 2 months ago :)

**Comment by propensive** [comment]
I'm happy to type my Sonatype password in if we can get to that stage! What needs to be done?

By the way, thanks for putting this into an issue - it's the only way I won't forget...

**Comment by nrinaudo** [comment]
I'll need to double check, but according to our gitter conversation on the subjet a while ago, what remains is typing your sonatype password :)

**Comment by propensive** [comment]
Ok, I just worked out the issue. The macros are not compatible, and I'll need to have different source. Scala 2.10 doesn't recognise `TermName`.

**Comment by propensive** [comment]
Ok, @nrinaudo: It was a three-character fix to the source which breaks it for Scala 2.11+, so I just made the change locally, `sbt publishSigned` it, then discarded the change, and 1.0.1 is now published for Scala 2.10, but don't tell anyone this is how I did it.

**Comment by nrinaudo** [comment]
But.. but does it mean you're going to have to do this for every new version?

(Also, how did you publish 1.0.0 then??)

**Comment by propensive** [comment]
Yep, I know. ;)

I may have done the same for 2.10, and forgotten, as I wish to do about this time. Maybe this delayed-release process should be a way of weaning people off 2.10...?
