### ISSUE TITLE
Improve error message for substitutions with wrong type

### ISSUE THREAD

**Issue by hagl** [propensive/contextual#15]
The error message for a substitution with a wrong type is very cryptic:

```
import contextual.examples._
import shell._
val x=0
sh"$x"
``` 
will give the following compile error:
```
<console>:19: error: type mismatch;
 found   : Int
 required: contextual.Interpolator.Embedded[String,_1.interpolator.type] where val _1: contextual.Prefix[contextual.examples.shell.ShellInterpolator.Output,contextual.examples.shell.ShellInterpolator.ContextType,contextual.examples.shell.ShellInterpolator.type]
       sh"$x"
           ^
```
For a user of the contextual library this message can be very difficult to understand and it only indirectly gives a hint that the substituted value should be of type `String`.
Is it possible to create a better message in this case?

**Comment by propensive** [comment]
There should be a nice solution to this. Thanks for raising the issue - I'll take a look at implementing it next week!

**Comment by xylo** [comment]
I get a similar error message although I've set `type Input = Any`.  How can there be an type mismatch when Int is a subclass of Any?  Is there any documentation about how to deal with non-Int parameters?

```
Error:(94, 100) type mismatch;
 found   : Int
 required: contextual.Interpolator.Embedded[Any,_1.interpolator.type] where val _1: contextual.Prefix[util.jpa.HqlInterpolator.Output,util.jpa.HqlInterpolator.ContextType,util.jpa.HqlInterpolator.type]
```
