### ISSUE TITLE
Error in example?

### ISSUE THREAD

**Issue by mkotsbak** [propensive/contextual#16]
Am I using it wrong or is it an error in the example?:

```
scala> bin"10111000"
<console>:35: error: type mismatch;
 found   : Array[Byte]
 required: contextual.examples.binary.BinParser.Output
       bin"10111000"
```

**Comment by propensive** [comment]
No, you're right, and we didn't check the example properly against a change that was made for the 1.0.1 release. I'll fix it now!

**Comment by propensive** [comment]
Actually, before I do, I'd like to check how the issue relates to @mielientiev's PR #9. I can't remember what was implemented yet, but I was a bit sloppy in checking the examples when the 1.0.1 release happened.
