### ISSUE TITLE
regex with a linter

### ISSUE THREAD

**Issue by fommil** [propensive/contextual#21]
this is basically nerd sniping of the highest order, but wouldn't it be nice to have a regex that linted its contents at compile time? I'm not aware of any such linter but surely there has got to be one.

**Comment by propensive** [comment]
Yes. How much work do you think is involved?

**Comment by fommil** [comment]
Probably not much to have something that just checks that the regex compiles (assuming no holes), but I have no idea how a linter would work.

**Comment by propensive** [comment]
We already have [this](http://co.ntextu.al/regex), but it's the linting that could probably use some improvements...

**Comment by fommil** [comment]
RTFM, Sam, RTFM.

**Comment by propensive** [comment]
This particular example is also begging for #5 to be implemented so you could write code like:
```scala
myString match {
  case r"fo*bar" => ...
  case r"(ba.)+" => ...
}
```

**Comment by propensive** [comment]
You could be forgiven for not expecting TFM to exist...

**Comment by fommil** [comment]
this does exist, but it was never published to maven... no `contextual-data` packages up there

**Comment by som-snytt** [comment]
Arrived here via #5 as I searched for issues for people with issues.
