### ISSUE TITLE
Provide access to `treatEscapes` through `Prefix`

### ISSUE THREAD

**Issue by jedesah** [propensive/contextual#25]
If I understand correctly, currently all compile time string interpolators defined using Contextual do not "treat" escapes. It seems to me like a fairly common use case to want the standard scala string escaping in one's compile time string interpolator.

Perhaps just an additional `Boolean` parameter to the [apply](http://co.ntextu.al/_/api/contextual/Prefix$.html#apply(interpolator:contextual.Interpolator,stringContext:StringContext):contextual.Prefix[interpolator.ContextType,interpolator.type]) method of the `Prefix` `Object` would suffice. Implementation should not be too difficult as the `String => String` function is exposed [here](https://www.scala-lang.org/api/current/scala/StringContext$.html#treatEscapes(str:String):String) in the std scala library.

**Comment by propensive** [comment]
I saw this problem, and I think I have a better solution to it... I have a couple more changes to make, but I should be able to release it soon.

**Comment by propensive** [comment]
I wish I could remember what I had in mind back when I wrote that...
