### ISSUE TITLE
Interpolators defined in the REPL cause `ClassNotFoundException`

### ISSUE THREAD

**Issue by propensive** [propensive/contextual#4]
Due, it seems, to some quirks of reflection in the REPL, calls to `Class.forName` do not appear to load the requested class, if it has just been defined. This means that currently it's not possible to define an interpolator and use it in the REPL.

**Comment by mielientiev** [comment]
@propensive 
I can reproduce it with sbt
I guess it's a bug in `macros.scala#getModule` in `Class.forName(s"$typeName$$")`
My assumptions is:  `Class.forName(s"$typeName$$")` tries to instantiate class in compile time. But interpolator wasn't compiled yet and JVM couldn't load the class

**Comment by propensive** [comment]
I think the class must be compiled then, because the method is being called from an instance of it, though it might be that it's a different classloader. Could you check whether the classloader that's being used in the macro (which doesn't find the class) is the same one as the one that's used if you call `Class.forName` in the REPL?

**Comment by mkotsbak** [comment]
Same issue in ScalaFiddle: https://scalafiddle.io/sf/WOGG0M5/1

**Comment by propensive** [comment]
Thanks for the additional datapoint, @mkotsbak!

**Comment by volth** [comment]
I have this issue with the most simple examples and without any fancy environments sbt or scala.js.
Just with scala-2.11.11 binary distribution and some pre-downloaded maven jars

Hello2.scala
```
import contextual.examples.hex._

object Hello extends App {
  println(hex"00")
}
```

run:
```
libs=$(dirname $(dirname $(readlink -f `which scala`)))/lib
                  
scalac -d zzz.jar \
  -Xplugin /home/user/.m2/repository/org/scalamacros/paradise_2.11.11/2.1.0/paradise_2.11.11-2.1.0.jar \
  -cp /home/user/.m2/repository/com/propensive/contextual_2.11/1.0.1/contextual_2.11-1.0.1.jar:/home/user/.m2/repository/org/typelevel/macro-compat_2.11/1.1.1/macro-compat_2.11-1.1.1.jar:$libs/scala-compiler.jar:$libs/scala-reflect.jar \
  Hello2.scala contextual/examples/src/main/scala/contextual/examples/hex.scala
```

result:
```
Hello2.scala:4: error: java.lang.ClassNotFoundException: contextual.examples.hex$HexParser$   
  println(hex"00")                                                                            
          ^                                                                                   
one error found                                                                               
```

**Comment by propensive** [comment]
Thanks for the really clear example, @volth! I'll see if I can work out what's going on...

**Comment by tues** [comment]
@volth: I think you need to compile `Hello2.scala` and `hex.scala` separately:
http://docs.scala-lang.org/overviews/macros/overview.html#using-macros-with-the-command-line-scala-compiler

So something like:

```
libs=$(dirname $(dirname $(readlink -f `which scala`)))/lib
classpath=/home/user/.m2/repository/com/propensive/contextual_2.11/1.0.1/contextual_2.11-1.0.1.jar:/home/user/.m2/repository/org/typelevel/macro-compat_2.11/1.1.1/macro-compat_2.11-1.1.1.jar:$libs/scala-compiler.jar:$libs/scala-reflect.jar
                  
scalac -d hex.jar \
  -Xplugin /home/user/.m2/repository/org/scalamacros/paradise_2.11.11/2.1.0/paradise_2.11.11-2.10..jar \
  -cp $classpath \
  contextual/examples/src/main/scala/contextual/examples/hex.scala

scalac -d zzz.jar \
  -Xplugin /home/user/.m2/repository/org/scalamacros/paradise_2.11.11/2.1.0/paradise_2.11.11-2.1.0.jar \
  -cp $classpath:hex.jar \
  Hello2.scala
```
