### ISSUE TITLE
Scala 2.13 release

### ISSUE THREAD

**Issue by francisdb** [propensive/contextual#49]
Amy plans for a Scala 2.13 release? Or would this be non-trivial?

**Comment by pjfanning** [comment]
Possibly blocked by https://github.com/milessabin/macro-compat/issues/87

**Comment by pjfanning** [comment]
Looks like macro-compat will not be released for scala 2.13 (https://github.com/milessabin/macro-compat/pull/85#issuecomment-500201690).

Would it be possible to drop the use of macro-compat from contextual?

**Comment by alonsodomin** [comment]
Contextual for Scala 2.13 is already available at Maven Central

**Comment by francisdb** [comment]
```
libraryDependencies += "com.propensive" %% "contextual" % "1.2.1"
```
